Add feed for onboarding-scripts
CreatorDev/Creator-feed pull request #15
Opened 2016-11-23 08:38 UTC by mar3kk

Signed-off-by: Marek Kubiczek <marek.kubiczek@imgtec.com>

2016-11-25 13:30 UTC, nikhil-zinjurde-imgtec requested changes

2016-11-25 13:30 UTC, nikhil-zinjurde-imgtec commented on onboarding-scripts/Makefile
> +PKG_SOURCE_URL:=$(TOPDIR)/../../packages/onboarding-scripts
The source URL should be remote i.e. https://github.com/CreatorDev/ci40-onboarding-scripts.git

Developers should set the source link locally for development purpose

2016-11-25 14:10 UTC, francois-berder-imgtec commented on onboarding-scripts/Makefile
> +
Do we actually need to define Build/Compile and Build/Clean if you are using the default functions ?

2016-11-25 14:11 UTC, francois-berder-imgtec commented on onboarding-scripts/Makefile
> +	cp -r $(PKG_INSTALL_DIR)/usr/lib/lua/* $(1)/usr/lib/lua/
$(CP)

2016-11-25 14:11 UTC, francois-berder-imgtec commented on onboarding-scripts/Makefile
> +#PKG_VERSION:=dev
remove comment

2016-11-28 09:39 UTC, francois-berder-imgtec commented on onboarding-scripts/Makefile
> +
You are missing PKG_MAINTAINER, PKG_LICENSE, PKG_LICENSE_FILE.

2016-11-28 09:39 UTC, francois-berder-imgtec commented on onboarding-scripts/Makefile
> +PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)
PKG_BUILD_DIR is defined by default as: $(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION).

2016-11-28 09:44 UTC, Ham22 commented on onboarding-scripts/Makefile
> +
Nope

2016-11-28 10:07 UTC, mar3kk commented on onboarding-scripts/Makefile
> +
What Do You think should I put in PKG_MAINTAINER? I do not see these fields defined in any of other packages.

2016-11-28 11:54 UTC, Ham22 commented on onboarding-scripts/Makefile
> +
For now we don't, we will worry about this if we ever get around to upstreaming it

2016-11-28 13:02 UTC, mar3kk commented on onboarding-scripts/Makefile
> +PKG_SOURCE_URL:=$(TOPDIR)/../../packages/onboarding-scripts
done

2016-11-28 13:03 UTC, mar3kk commented on onboarding-scripts/Makefile
> +PKG_SOURCE_URL:=$(TOPDIR)/../../packages/onboarding-scripts
done

2016-11-28 15:59 UTC, francois-berder-imgtec commented on onboarding-scripts/Makefile
> +PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)
No need to redefine PKG_BUILD_DIR. Remove it

2016-11-28 16:00 UTC, ghost commented on onboarding-scripts/Makefile
> +CMAKE_OPTIONS += -DSTAGING_DIR=$(STAGING_DIR)
Why do you need to set this option ?

2016-11-28 16:01 UTC, francois-berder-imgtec commented on onboarding-scripts/Makefile
> +	$(CP) -r $(PKG_INSTALL_DIR)/usr/lib/lua/* $(1)/usr/lib/lua/
no need for the -r option.
It is already part of the definition of CP in rules.mk

2016-11-28 16:02 UTC, ghost commented on onboarding-scripts/Makefile
> +	$(INSTALL_DIR) $(1)/www
Could you group INSTALL_DIR and CP ? So you install www, binaries,libraries...

2016-11-28 16:05 UTC, francois-berder-imgtec commented on onboarding-scripts/Makefile
> +PKG_VERSION:=v0.1.0
It seems that very few packages have PKG_VERSION defined as v[number]. I suggest
```
PKG_VERSION:=0.1.0
...
PKG_SOURCE_VERSION:=v$(PKG_VERSION)
```

2016-11-28 17:55 UTC, mar3kk commented on onboarding-scripts/Makefile
> +CMAKE_OPTIONS += -DSTAGING_DIR=$(STAGING_DIR)
I believe this is copied from other project and not needed. Removed.

2016-11-28 17:55 UTC, mar3kk commented on onboarding-scripts/Makefile
> +	$(CP) -r $(PKG_INSTALL_DIR)/usr/lib/lua/* $(1)/usr/lib/lua/
fixed

2016-11-28 17:55 UTC, mar3kk commented on onboarding-scripts/Makefile
> +	$(INSTALL_DIR) $(1)/www
grouped

2016-11-28 17:56 UTC, mar3kk commented on onboarding-scripts/Makefile
> +PKG_VERSION:=v0.1.0
I decided to go with pure version number for tags as well. fixed.

2016-11-29 10:48 UTC, ghost approved these changes

2016-11-29 11:11 UTC, nikhil-zinjurde-imgtec approved these changes

2016-11-29 15:06 UTC, merged