[WIP] Add info-daemon feed
CreatorDev/Creator-feed pull request #17
Opened 2016-11-24 09:34 UTC by mar3kk

Signed-off-by: Marek Kubiczek <marek.kubiczek@imgtec.com>

2016-11-25 13:29 UTC, nikhil-zinjurde-imgtec submitted a review, later dismissed

2016-11-25 13:29 UTC, nikhil-zinjurde-imgtec commented on info-daemn/Makefile
> +PKG_SOURCE_URL:=$(TOPDIR)/../../packages/info-daemon
The source URL should be remote i.e. https://github.com/CreatorDev/ci40-info-daemon.git

Developers should set the source link locally for development purpose

2016-11-25 13:29 UTC, nikhil-zinjurde-imgtec commented on info-daemn/Makefile
> +PKG_VERSION:=HEAD
The version should be a tag of the feed repo

2016-11-25 14:13 UTC, francois-berder-imgtec commented
Add PKG_LICENSE and PKG_LICENSE_FILE.

2016-11-28 19:11 UTC, mar3kk commented on info-daemn/Makefile
> +PKG_VERSION:=HEAD
fixed

2016-11-28 19:11 UTC, mar3kk commented on info-daemn/Makefile
> +PKG_SOURCE_URL:=$(TOPDIR)/../../packages/info-daemon
fixed

2016-11-29 10:03 UTC, Ham22 requested changes

2016-11-29 10:03 UTC, Ham22 commented on info-daemn/Makefile
> +	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/* $(1)/usr/bin
This should install from PKG_BUILD_DIR not the install directory

2016-11-29 10:04 UTC, francois-berder-imgtec commented on info-daemn/Makefile
> +PKG_SOURCE_VERSION:=$(PKG_VERSION)
PKG_SOURCE_VERSION must match the tag of the release you want to compile. Hence, it should be equal 
to v$(PKG_VERSION) instead of $(PKG_VERSION).

2016-11-29 10:05 UTC, mar3kk commented on info-daemn/Makefile
> +PKG_SOURCE_VERSION:=$(PKG_VERSION)
I updated the tag https://github.com/CreatorDev/ci40-info-daemon/releases/tag/0.1.0

2016-11-29 10:12 UTC, francois-berder-imgtec commented on info-daemn/Makefile
> +PKG_SOURCE_VERSION:=$(PKG_VERSION)
ok fine.

2016-11-29 10:45 UTC, ghost approved these changes

2016-11-29 10:58 UTC, Ham22 commented on info-daemn/Makefile
> +	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/* $(1)/usr/bin
Hmm despite the docs a grep through the code show that both are used so forget this comment.

2016-11-29 15:08 UTC, Ham22 approved these changes

2016-11-30 13:39 UTC, merged